### ISSUE TITLE
Update Bloc version to 5.0.0

### ISSUE THREAD

**Issue by excogitatr** [KiritchoukC/vscode-ext_flutter-clean-architecture#4]
Bloc version has been updated to v5.0.0. Two notifications prompts when enabling the extension similar to the issue #2

**Comment by KiritchoukC** [comment]
Hi @excogitatr,

Thanks for raising this issue.

I'll look at it asap

**Comment by KiritchoukC** [comment]
[Extension updated to version 1.0.1](https://marketplace.visualstudio.com/items?itemName=KiritchoukC.flutter-clean-architecture&ssr=false#overview)

**Comment by ericomine** [comment]
Hello. I see Cubit templates have been added in this update. How would I go about scaffolding the feature with Cubit instead of Bloc? I have not found any extra option in the context menu, neither any setting related to this extension.

If modifications are necessary for this functionality to be implemented, I can help with a PR.

**Comment by KiritchoukC** [comment]
At the moment, the extension does not provide a way to scaffold a feature with Cubit instead of Bloc.

You can raise an issue about it.

Your help is appreciated 😄
